import 'dotenv/config'
import express from 'express'; import multer from 'multer'; import jwt from 'jsonwebtoken'; import path from 'node:path'; import fs from 'node:fs'; import crypto from 'node:crypto'; import { Readable } from 'node:stream'
import { db, save } from './storage.js'; import { analyzeMedia } from './ai.js'
import { getStorageProvider } from './providers/storage.js'
const app=express(), port=process.env.PORT||3001, secret=process.env.JWT_SECRET
const uploadDir=path.resolve('server/uploads'); fs.mkdirSync(uploadDir,{recursive:true})
app.use(express.json({limit:'1mb'})); app.use('/uploads',express.static(uploadDir))
const auth=(req,res,next)=>{ try { req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret); next() } catch {res.status(401).json({error:'Authentication required'})} }
const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
const maxUploadBytes=(Number(process.env.MAX_UPLOAD_MB)||20)*1024*1024
const appsBridgeBytes=(Number(process.env.APPS_SCRIPT_MAX_BRIDGE_MB)||4)*1024*1024
const uploadLimit=(process.env.STORAGE_PROVIDER||'local').toLowerCase()==='apps-script'?Math.min(maxUploadBytes,appsBridgeBytes):maxUploadBytes
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:uploadLimit},fileFilter:(_r,f,cb)=>cb(null,allowed.has(f.mimetype))})
app.get('/api/public',(req,res)=>{const x=db(); res.json({media:x.media.filter(m=>m.published),achievements:x.achievements.filter(a=>a.published),projects:x.projects,team:x.team,links:x.links,settings:x.settings,categories:x.categories})})
app.post('/api/auth/login',(req,res)=>{ if(!secret||!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD) return res.status(503).json({error:'Admin login is not configured. Set ADMIN_EMAIL, ADMIN_PASSWORD and JWT_SECRET in .env.'}); if(req.body.email!==process.env.ADMIN_EMAIL||req.body.password!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:'Invalid email or password'}); res.json({token:jwt.sign({role:'admin'},secret,{expiresIn:'8h'})}) })
app.get('/api/admin/data',auth,(req,res)=>res.json(db()))
app.get('/api/admin/media/:id/preview',auth,async(req,res)=>{const item=db().media.find(m=>m.id===req.params.id);if(!item)return res.status(404).json({error:'Media not found.'});if(!item.storageKey||!item.storageProvider)return res.status(404).json({error:'Preview unavailable for this media.'});try{const file=await getStorageProvider(item.storageProvider).get(item.storageKey);res.setHeader('Content-Type',file.mimeType||item.mimeType||'application/octet-stream');res.setHeader('Content-Disposition','inline');res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');if(file.webStream)Readable.fromWeb(file.webStream).pipe(res);else res.end(file.buffer)}catch(error){const message=String(error?.message||'');if(/size|limit|large/i.test(message))return res.status(413).json({error:'Preview unavailable for this file size.'});res.status(502).json({error:'Preview unavailable for this media.'})}})
app.get('/api/media/:provider/:key',async(req,res)=>{const x=db();const item=x.media.find(m=>m.published&&m.storageProvider===req.params.provider&&m.storageKey===req.params.key);if(!item)return res.status(404).end();try{const provider=getStorageProvider(req.params.provider);const file=await provider.get(req.params.key);res.setHeader('Content-Type',file.mimeType||item.mimeType||'application/octet-stream');res.setHeader('Cache-Control','public, max-age=3600');if(file.webStream) Readable.fromWeb(file.webStream).pipe(res); else res.end(file.buffer)}catch(error){res.status(502).json({error:'Media is temporarily unavailable.'})}})
app.post('/api/admin/media',auth,upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Use a supported image/video under the size limit.'});const provider=getStorageProvider();let stored;try{stored=await provider.upload({buffer:req.file.buffer,mimeType:req.file.mimetype,originalName:req.file.originalname})}catch(error){return res.status(502).json({error:error.message||'Media storage upload failed.'})}const record={id:crypto.randomUUID(),originalName:req.file.originalname,url:stored.url,type:req.file.mimetype.startsWith('video/')?'video':'image',mimeType:req.file.mimetype,storageProvider:stored.provider,storageKey:stored.storageKey,createdAt:new Date().toISOString(),published:false,title:'',description:'',category:'Other',tags:[],altText:''};const suggested=await analyzeMedia(record,{buffer:req.file.buffer,mimeType:req.file.mimetype});Object.assign(record,{title:suggested.title,description:suggested.description,category:suggested.category,tags:suggested.tags,altText:suggested.altText,ai:suggested});const x=db();x.media.unshift(record);save(x);res.status(201).json(record)})
app.patch('/api/admin/:collection/:id',auth,(req,res)=>{const x=db();const list=x[req.params.collection];if(!Array.isArray(list))return res.status(404).json({error:'Unknown collection'});const item=list.find(i=>i.id===req.params.id);if(!item)return res.status(404).json({error:'Not found'});Object.assign(item,req.body,{id:item.id});save(x);res.json(item)})
app.post('/api/admin/:collection',auth,(req,res)=>{const x=db();if(!Array.isArray(x[req.params.collection]))return res.status(404).json({error:'Unknown collection'});const item={id:crypto.randomUUID(),...req.body};x[req.params.collection].push(item);save(x);res.status(201).json(item)})
app.delete('/api/admin/:collection/:id',auth,async(req,res)=>{const x=db();if(!Array.isArray(x[req.params.collection]))return res.status(404).json({error:'Unknown collection'});const item=x[req.params.collection].find(i=>i.id===req.params.id);if(req.params.collection==='media'&&item?.storageKey){try{await getStorageProvider(item.storageProvider).delete(item.storageKey)}catch(error){return res.status(502).json({error:'Could not delete the stored media. The CMS record was kept.'})}}x[req.params.collection]=x[req.params.collection].filter(i=>i.id!==req.params.id);save(x);res.status(204).end()})
app.put('/api/admin/config/:key',auth,(req,res)=>{const x=db();if(!['links','settings','categories'].includes(req.params.key))return res.status(404).json({error:'Unknown config'});x[req.params.key]=req.body;save(x);res.json(x[req.params.key])})
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:'Upload failed: '+err.message});res.status(500).json({error:'Server error'})})
app.listen(port,()=>console.log(`KripaBot API on http://localhost:${port}`))
